# Generated by Django 2.1 on 2018-09-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0002_auto_20180917_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150),
        ),
    ]
